apiVersion: v1
kind: Service
metadata:
  name: cloud-app
  namespace: cloud-app
spec:
  # ClusterIP exposes the app internally
  # External traffic is handled by the Ingress -> GCP Load Balancer
  type: ClusterIP
  selector:
    app: cloud-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
